### PR TITLE
fix: Set backup_retention_period also as computed

### LINKED ISSUE #322: `backup_retention_period` inconsistent result
**Describe the bug**
With `v0.6.0`, `terraform apply` fails when backup retention period is omitted.
```shell
- Installing enterprisedb/biganimal v0.6.0...
- Installed enterprisedb/biganimal v0.6.0 (signed by a HashiCorp partner, key ID EBC45A0017D06CF5)
```
```shell
  # module.biganimal_us_east4["dbt2"].biganimal_cluster.instance will be created
  + resource "biganimal_cluster" "instance" {
      + cloud_provider                = "gcp"
      + cluster_id                    = (known after apply)
      + cluster_name                  = (known after apply)
      + cluster_type                  = (known after apply)
      + connection_uri                = (known after apply)
      + created_at                    = (known after apply)
      + csp_auth                      = false
      + faraway_replica_ids           = (known after apply)
      + first_recoverability_point_at = (known after apply)
      + id                            = (known after apply)
      + instance_type                 = "gcp:e2-highcpu-8"
      + logs_url                      = (known after apply)
      + metrics_url                   = (known after apply)
      + password                      = "1234567890zyxu"
      + pg_type                       = "postgres"
      + pg_version                    = "14"
      + phase                         = (known after apply)
      + private_networking            = false
      + project_id                    = "<ba_project_id>"
      + read_only_connections         = false
      + region                        = "us-east4"
      + resizing_pvc                  = (known after apply)
      + ro_connection_uri             = (known after apply)
      + allowed_ip_ranges {
          + cidr_block = "0.0.0.0/0"
        }
      + cluster_architecture {
          + id    = "single"
          + name  = (known after apply)
          + nodes = 1
        }
      + pg_config {
          + name  = "autovacuum_max_workers"
          + value = "5"
        }
      + pg_config {
          + name  = "autovacuum_vacuum_cost_limit"
          + value = "3000"
        }
      + pg_config {
          + name  = "checkpoint_completion_target"
          + value = "0.9"
        }
      + pg_config {
          + name  = "checkpoint_timeout"
          + value = "15min"
        }
      + pg_config {
          + name  = "cpu_tuple_cost"
          + value = "0.03"
        }
      + pg_config {
          + name  = "effective_cache_size"
          + value = "0.75 * ram"
        }
      + pg_config {
          + name  = "maintenance_work_mem"
          + value = "(0.15 * (ram - shared_buffers) / autovacuum_max_workers) > 1GB ? 1GB : (0.15 * (ram - shared_buffers) / autovacuum_max_workers)"
        }
      + pg_config {
          + name  = "random_page_cost"
          + value = "1.1"
        }
      + pg_config {
          + name  = "shared_buffers"
          + value = "((0.25 * ram) > 80GB) ? 80GB : (0.25 * ram)"
        }
      + pg_config {
          + name  = "tcp_keepalives_idle"
          + value = "120"
        }
      + pg_config {
          + name  = "tcp_keepalives_interval"
          + value = "30"
        }
      + pg_config {
          + name  = "wal_buffers"
          + value = "64MB"
        }
      + pg_config {
          + name  = "wal_compression"
          + value = "on"
        }
      + storage {
          + iops              = (known after apply)
          + size              = "4096 Gi"
          + throughput        = (known after apply)
          + volume_properties = "pd-ssd"
          + volume_type       = "pd-ssd"
        }
    }
```
```shell
module.biganimal_us_east4["dbt2"].biganimal_cluster.instance: Still creating... [6m0s elapsed]
module.biganimal_us_east4["dbt2"].biganimal_cluster.instance: Still creating... [6m10s elapsed]
module.biganimal_us_east4["dbt2"].biganimal_cluster.instance: Still creating... [6m20s elapsed]
module.biganimal_us_east4["dbt2"].biganimal_cluster.instance: Still creating... [6m30s elapsed]
╷
│ Warning: PG config changed
│ 
│   with module.biganimal_us_east4["dbt2"].biganimal_cluster.instance,
│   on modules/biganimal/main.tf line 1, in resource "biganimal_cluster" "instance":
│    1: resource "biganimal_cluster" "instance" {
│ 
│ PG config changed from [] to [{"name":"wal_buffers","value":"64MB"}
│ {"name":"wal_compression","value":"on"}
│ {"name":"cpu_tuple_cost","value":"0.03"}
│ {"name":"effective_cache_size","value":"0.75 * ram"}
│ {"name":"random_page_cost","value":"1.1"}
│ {"name":"tcp_keepalives_idle","value":"120"}
│ {"name":"maintenance_work_mem","value":"(0.15 * (ram - shared_buffers) /
│ autovacuum_max_workers) > 1GB ? 1GB : (0.15 * (ram - shared_buffers) /
│ autovacuum_max_workers)"} {"name":"shared_buffers","value":"((0.25 * ram) >
│ 80GB) ? 80GB : (0.25 * ram)"}
│ {"name":"tcp_keepalives_interval","value":"30"}
│ {"name":"autovacuum_max_workers","value":"5"}
│ {"name":"autovacuum_vacuum_cost_limit","value":"3000"}
│ {"name":"checkpoint_completion_target","value":"0.9"}
│ {"name":"checkpoint_timeout","value":"15min"}]
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.biganimal_us_east4["dbt2"].biganimal_cluster.instance, provider
│ "provider[\"registry.terraform.io/enterprisedb/biganimal\"].default"
│ produced an unexpected new value: .backup_retention_period: was null, but
│ now cty.StringVal("30d").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
program finished with exit code 1
elapsedTime=441.867639
```

**To Reproduce**
Do not set/omit backup retention period with biganimal provider `v0.6.0`

**Expected behavior**
`terraform apply` success.
```
Apply complete! Resources: 15 added, 0 changed, 0 destroyed.
Outputs:
servers = <sensitive>
spec = <sensitive>
```

**Terraform and Provider Version:**
Please share the `terraform version` output
```
Terraform v1.3.6
on linux_amd64
```

**Affected Resource(s):**
Please list the resources as a list, for example:
- biganimal_cluster resource

### PR DESCRIPTION
**Pull request by serdardalgic**
We also need the Unknown PlanModifier, in case it's not provided in the config

Fixes #322. 

Please review.

### CODE REVIEW

File: pkg/provider/resource_cluster.go [hunk 1]
```diff
@@ -253,6 +253,8 @@ func (c *clusterResource) Schema(ctx context.Context, req resource.SchemaRequest
 			"backup_retention_period": schema.StringAttribute{
 				MarkdownDescription: "Backup retention period. For example, \"7d\", \"2w\", or \"3m\".",
 				Optional:            true,
+				Computed:            true,
```
Comment (wai-wong-edb) [inline pkg/provider/resource_cluster.go:256]: Would it be better to just have it as required? On the UI it is required

**Review by wai-wong-edb — CHANGES_REQUESTED** [review]

**Review by wai-wong-edb — APPROVED** [review]
