### PR TITLE
fix: Show most_recent cluster when there are multiple with the same name

### LINKED ISSUE #43: Update cluster data_source to handle multiple clusters with the same name
In BigAnimal, a cluster is identified by either [provider, region, name] or [clusterid], cluster's name itself won't be able to identify a cluster by itself.

In the current implementation, we use cluster names to fetch the clusters via data_sources. If there are multiple clusters with the same name, [we return 404](https://github.com/EnterpriseDB/terraform-provider-biganimal/blob/072f3aa96819265ddd3ce57d02f350c7c3364a61/pkg/api/clusterClient.go#L97). There is a bug reported by @kunliuedb at #25. 

I'd like to propose the following solution:
* `biganimal_cluster` data_source would get `cluster_name` as an argument and would fail if there are more than 1 clusters returned. The error message should be improved to inform the user that there are multiple clusters with the same name. 
* In the future, we can think of providing a solution like `the most recent` one. This can be a data_source argument to overcome the fail. 
* We can introduce a new data_source called `biganimal_cluster_ids` that would return the ids of the clusters with a given name
* We can include `cluster_ids` as an argument for the `biganimal_cluster` data source. This data_source would check if there is a name or cluster_id so that it can fetch the cluster information from the API, and return as a data_source. Name and cluster_id should be mutually exclusive and terraform should fail if they both exist in the data_source.

### PR DESCRIPTION
**Pull request by serdardalgic**
This fixes #43 and #25. 

For clarity, I sorted the `clusters.data` response according to the Seconds. For better granularity, Nanos check can also be included. 

`most_recent` field has a default value of `true`. 

Please review.

### CODE REVIEW

File: pkg/api/cluster_client.go [hunk 1]
```diff
@@ -80,7 +81,11 @@ func (c ClusterClient) ReadByName(ctx context.Context, projectId, name string) (
 	}
 
 	if len(clusters.Data) != 1 {
-		return &models.Cluster{}, Error404
+		if most_recent {
+			sort.Slice(clusters.Data, func(i, j int) bool { return clusters.Data[i].CreatedAt.Seconds > clusters.Data[j].CreatedAt.Seconds })
+		} else {
+			return &models.Cluster{}, Error404
```
Comment (kunliuedb) [inline pkg/api/cluster_client.go:87]: Just suggest to return meaningful message here instead of `resource not found`. If it falls into this branch, it means that there is more than one resource with the same cluster name in the same project (which I admit it's rare).

Comment (serdardalgic) [reply pkg/api/cluster_client.go:87]: but it can happen, right? :) So, I'm updating the error message, thanks for the suggestion @kunliuedb 👍

Comment (serdardalgic) [reply pkg/api/cluster_client.go]: Wrote [here](https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/118#issuecomment-1385347383)

File: pkg/api/cluster_client.go [hunk 2]
```diff
@@ -80,7 +81,11 @@ func (c ClusterClient) ReadByName(ctx context.Context, projectId, name string) (
 	}
 
 	if len(clusters.Data) != 1 {
-		return &models.Cluster{}, Error404
+		if most_recent {
+			sort.Slice(clusters.Data, func(i, j int) bool { return clusters.Data[i].CreatedAt.Seconds > clusters.Data[j].CreatedAt.Seconds })
+		} else {
+			return &models.Cluster{}, ErrorClustersSameName
```
Comment (dhilipkumars) [inline pkg/api/cluster_client.go:87]: should `most_recent` be a default option if multiple clusters found? 
may be print a log saying that
`we found multiple clusters but returned the most recent one?`

**Review by dhilipkumars — COMMENTED** [review]
MinorComment

File: pkg/api/cluster_client.go (hunk 2 above)
Comment (dhilipkumars) [reply pkg/api/cluster_client.go:87]: the reason im thinking is we made the api-call, we got the data and we are dropping it at the last min and asking the user to make another call?

**Review by kunliuedb — DISMISSED** [review]
LGTM

File: pkg/api/cluster_client.go (hunk 2 above)
Comment (serdardalgic) [reply pkg/api/cluster_client.go:87]: That's a good suggestion @dhilipkumars. 
In our current design, the client sends the return value and the errors. When we find two or more clusters with the same name, we can return this info from the client and turn it into a `Warning` level Diagnostic, but I need to think about how to do that. 

For now, the best I can offer is creating a ticket for this and adding a `tflog.Info` when most_recent is true.

Comment (serdardalgic) [reply pkg/api/cluster_client.go:87]: Actually, I'm not sure about the `tflog.Info` there because it's the client code. We're trying to keep the client code as terraform-agnostic as possible. So, I will write the debug info in the ticket as well.

Comment (serdardalgic) [reply pkg/api/cluster_client.go:87]: I created #121 so that we can tackle the problem in a dedicated time. 
Do you agree with that @dhilipkumars? If It's not a blocker, I'd like to merge this PR first, and then tackle the Warning system later.

Comment (dhilipkumars) [reply pkg/api/cluster_client.go:87]: Thanks @serdardalgic im resolving this comment
